### ISSUE TITLE
Feature request: allow line breaks after custom characters

### ISSUE THREAD

**Issue by cfit-sw** [parubok/multiline-label#1]
Hi,
I have a use case where file paths are displayed in a multiline label. It would be great if line breaks could be configured to also be permitted after directory seperators ('/' or '\', depending on the plattform), or other characters for custom use cases.

As far as i can tell, the getNextLine method of the WidthTextLayout class would need to be altered (along with some constructors to pass this option down), but since the class is final, i can not extend it.

Would you consider implementing this feature?

**Comment by parubok** [comment]
Thank you for reporting this. I'll have a look.

**Comment by parubok** [comment]
Hi! I released a new version 1.19 which includes a support for custom separator characters. Please try it and let me know if it works for you.
