### ISSUE TITLE
Allow copy and paste text from a multiline box

### ISSUE THREAD

**Issue by mokun** [parubok/multiline-label#2]
Is there a way to allow the use of a mouse/keyboard to copy and paste some text from a multiline box to clipboard in windows ? 

I know JTextField can do that. I wonder if you can add this capability to multiline label.

Thanks !

**Comment by parubok** [comment]
Hi!
Class `MultilineLabel` has public `copy()` method.
To paste, use `setText` method.
You will need to setup mouse/keyboard listeners - just like for any regular Swing component.
